// app/javascript/projects/node_component.tsx
import * as React from 'react'
import { Control, Node, Socket } from 'rete-react-render-plugin'
import $ from 'jquery'

export class NodeComponent extends Node {
  props: any // TODO
  state: any // TODO
  
  render() {
    const { node, editor, bindSocket, bindControl } = this.props
    const { outputs, controls, inputs, selected } = this.state

    setTimeout(() => $('[title]').tooltip('dispose').tooltip())

    return (
      <div className={`node ${selected}`} style={{
        boxShadow: "0px 0px 8px rgba(0, 0, 0, 0.25)",
        background: "rgba(0, 0, 0, 0.5)",
        color: "white",
        borderRadius: "4px",
        border: "solid 3px transparent",
        cursor: "pointer",
        minWidth: "250px",
        height: "auto",
        boxSizing: "content-box",
        position: "relative",
        userSelect: "none",
      }}>
        <div style={{padding: "calc(.5rem - 3px)"}} className="d-flex align-items-center">
          <input
            type="text"
            className="form-control bg-dark text-light border-0"
            style={{boxShadow: "none", width: "0px", flexGrow: "1"}}
            placeholder={node.name}
            value={node.data.name}
            onChange={e => node.data.name = e.target.value}
            onPointerDown={e => e.stopPropagation()}
            onDoubleClick={e => e.stopPropagation()}
          />
          {
            node.meta.errorMessage &&
            <i
              className="fas fa-exclamation-triangle ml-2 mb-1 text-danger"
              title={node.meta.errorMessage}
            />
          }
        </div>
        <div style={{display: "flex", justifyContent: "space-between"}}>
          <div>
            {inputs.map(input => (
              <div className="input" key={input.key}>
                <Socket type="input" socket={input.socket} io={input} innerRef={bindSocket} />
                {!input.showControl() && <div className="input-title">{input.name}</div>}
                {input.showControl() && <Control className="input-control" control={input.control} innerRef={bindControl} />}
              </div>
            ))}
          </div>
          <div>
            {outputs.map((output) => (
              <div className="output" key={output.key}>
                <div className="output-title">{output.name}</div>
                <Socket type="output" socket={output.socket} io={output} innerRef={bindSocket} />
              </div>
            ))}
          </div>
        </div>
        {controls.map(control => (
          <Control className="control" key={control.key} control={control} innerRef={bindControl} />
        ))}
      </div>
    )
  }
}

// app/typescript/modelling/Node.vue
<template>
  <div
    class="node"
    :class="{ 'node--selected': selected() }"
  >
    <div style="padding: calc(.5rem - 3px)" class="d-flex align-items-center">
      <input
        type="text"
        class="form-control bg-dark text-light border-0"
        style="box-shadow: none; width: 0px; flex-grow: 1"
        :placeholder="node.name"
        :value="node.data.name"
        @input="node.data.name = $event.target.value"
        @pointerdown.stop
        @dblclick.stop
      >
      <i v-if="node.meta.errorMessage" class="fas fa-exclamation-triangle ml-2 mb-1 text-danger" :title="node.meta.errorMessage"></i>
    </div>

    <div class="node__io">
      <div>
        <div class="node__input" v-for="input in inputs()" :key="input.key">
          <Socket v-socket:input="input" type="input" :socket="input.socket"/>
          <div class="node__input-title" v-show="!input.showControl()">{{ input.name }}</div>
          <div class="node__input-control" v-show="input.showControl()" v-control="input.control"></div>
        </div>
      </div>

      <div>
        <div class="node__output" v-for="output in outputs()" :key="output.key">
          <div class="node__output-title">{{ output.name }}</div>
          <Socket v-socket:output="output" type="output" :socket="output.socket"/>
        </div>
      </div>
    </div>

    <div class="node__control" v-for="control in controls()" v-control="control" :key="control.key"></div>
  </div>
</template>

<script>
import $ from 'jquery'
import mixin from 'rete-vue-render-plugin/src/mixin'
import Socket from './Socket'

export default {
  mixins: [mixin],
  components: {
    Socket
  },
  updated: function () {
    this.$nextTick(function () {
      $('[title]').tooltip('dispose').tooltip()
    })
  }
}
</script>

<style lang="scss" scoped>
$node-color: rgba(0, 0, 0, 0.5);

.node {
  box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.25);
  background: $node-color;
  color: white;
  border-radius: 4px;
  border: solid 3px transparent;
  cursor: pointer;
  min-width: 180px;
  height: auto;
  box-sizing: content-box;
  position: relative;
  user-select: none;

  &:hover {
    background: lighten($node-color,4%);
  }

  &--selected {
    border-color: white;
  }

  &__io {
    display: flex;
    justify-content: space-between;
  }

  &__input, &__output {
    margin: .25rem 0rem;
  }

  &__input {
    text-align: left;
  }

  &__output {
    text-align: right;
  }

  &__input-title, &__output-title {
    vertical-align: middle;
    color: white;
    display: inline-block;
    line-height: 1rem;
  }

  &__input-control {
    z-index: 1;
    width: calc(100% - 1rem);
    vertical-align: middle;
    display: inline-block;
  }

  &__control {
    margin: .5rem;
  }
}
</style>
