// app/javascript/projects/modelling/controls/barchart.tsx
import * as React from 'react'
import { Control } from 'rete'
import * as d3 from 'd3'

export interface BarChartVariable {
    label: string
    value: number
}

interface BarChartProps {
    title?: string
    variables: BarChartVariable[]
}

interface YAxisProps {
    scale: d3.ScaleBand<string>
    transform: string
}

interface XAxisProps {
    scale: d3.ScaleLinear<number, number, never>
    transform: string
}

interface BarsProps {
    variables: BarChartVariable[]
    scaleX: XAxisProps["scale"]
    scaleY: YAxisProps["scale"]
}

function YAxis({ scale, transform }: YAxisProps) {
    const ref = React.useRef<SVGGElement>(null)

    React.useEffect(() => {
        if (ref.current) {
            d3.select(ref.current).call(d3.axisLeft(scale)).style("font-size", "14px").style("font-weight", "500")
        }
    }, [scale])

    return <g ref={ref} transform={transform} />
}

function XAxis({ scale, transform }: XAxisProps) {
    const ref = React.useRef<SVGGElement>(null)

    React.useEffect(() => {
        if (ref.current) {
            d3.select(ref.current).call(d3.axisBottom(scale.nice())).style("font-size", "14px")
        }
    }, [scale])

    return <g ref={ref} transform={transform} />
}

function Bars({ variables, scaleX, scaleY }: BarsProps) {
    return (
        <>
            {variables.map(({ value, label }) => (
                <>
                    <rect
                        key={`bar-${label}`}
                        width={scaleX(value)}
                        height={scaleY.bandwidth() / 2}
                        x={0}
                        y={Number(scaleY(label)) + (scaleY.bandwidth() * .25)}
                        fill={d3.schemeSet3[value > 0 ? 0 : 3]}
                    />
                    <text
                        key={`text-${label}`}
                        x={scaleX(value) + Math.sign(value) * 4}
                        y={Number(scaleY(label)) + (scaleY.bandwidth() * .50)}
                        dy={"0.35em"}
                        fontSize="12"
                        fontWeight="300"
                    >
                        {value.toLocaleString(undefined, { maximumSignificantDigits: 3 })}
                    </text>
                </>
            ))}
        </>
    )

}

const BarChart = ({ variables, title }: BarChartProps) => {

    if (variables.length === 0) { return (<div></div>) }

    if (!title) title = ""

    const labelPadding = Math.max(...variables.map(v => v.label.length)) * 7
    const margin = { top: 10, right: 50, bottom: 20, left: 45 + labelPadding }
    const width = 600 - margin.left - margin.right + (labelPadding / 2)
    const height = (80 + (variables.length * 50)) - margin.top - margin.bottom //calc height based on n 

    const scaleY = d3.scaleBand()
        .domain(variables.map(({ label }) => label))
        .range([0, height])


    const scaleX = d3.scaleLinear()
        .domain([Math.max(...variables.map(({ value }) => value)) * 1.1, 0])
        .range([width, 0]);


    return (
        <figure
            className='bg-white text-dark p-4'>
            <svg
                width={width + margin.left + margin.right}
                height={height + margin.top + margin.bottom}
            >
                <g transform={`translate(${margin.left}, ${margin.top})`}>
                    <Bars variables={variables} scaleX={scaleX} scaleY={scaleY} />
                    <YAxis scale={scaleY} transform={`translate(0, 0)`} />
                    <XAxis scale={scaleX} transform={`translate(0, ${height})`} />
                </g>

            </svg>
            <figcaption className="text-center mt-3" >{title}</figcaption>
        </figure >
    )
}

export class BarChartControl extends Control {
    props: BarChartProps
    component: (props: BarChartProps) => JSX.Element

    constructor(key: string) {
        super(key)
        this.props = {
            variables: []
        }
        this.component = BarChart
    }

    setTitle(title: string): void {
        this.props.title = title
    }

    setVariables(variables: BarChartVariable[]): void {
        this.props.variables = variables
    }

}

// app/typescript/modelling/controls/BarChart.vue
<template>
  <figure class="bg-white text-dark text-nowrap p-4">
    <svg ref="svg">
      <rect
        v-for="variable in variables"
        :fill="d3.schemeSet3[variable.value > 0 ? 0 : 3]"
        :x="x(Math.min(variable.value, 0))"
        :y="y(variable.name)"
        :width="Math.abs(x(variable.value) - x(0))"
        :height="y.bandwidth()"
      />
      <text
        v-for="variable in variables"
        :text-anchor="variable.value < 0 ? 'end' : 'start'"
        :x="x(variable.value) + Math.sign(variable.value) * 4"
        :y="y(variable.name) + y.bandwidth() / 2"
        dy="0.35em"
        font-size="12"
        font-weight="300"
      >{{ variable.value.toLocaleString(undefined, { maximumSignificantDigits: 3 }) }}</text>
      <g v-call="drawXAxis" :transform="`translate(0,${height})`"/>
      <g v-call="drawYAxis" :transform="`translate(${clamp(x(0), 0, width)},0)`"/>
    </svg>
    <figcaption class="text-center mt-3" style="font-weight: 500">{{ title }}</figcaption>
  </figure>
</template>

<script>
import * as d3 from 'd3'
import clamp from 'lodash/clamp'

export default {
  props: [
    'title',
    'variables',
  ],
  data() {
    return {
      d3,
      width: 350,
    }
  },
  computed: {
    x() {
      return d3
        .scaleLinear()
        .domain(d3.extent([0].concat(this.variables.map(variable => variable.value))))
        .rangeRound([0, 350])
        .nice()
    },
    y() {
      return d3
        .scaleBand()
        .domain(this.variables.map(variable => variable.name))
        .rangeRound([0, this.height])
        .padding(0.2)
    },
    height() {
      return this.variables.length * 45
    },
  },
  mounted() {
    this.updateBoundingBox()
  },
  updated() {
    this.updateBoundingBox()
  },
  methods: {
    clamp,
    drawXAxis(g) {
      g.call(d3.axisBottom(this.x))
    },
    drawYAxis(g) {
      g.attr("font-size", null)
      g.attr("font-family", null)
      g.attr("font-weight", "500")
      g.call(
        d3.axisLeft(this.y)
          .tickSize(0)
          .tickPadding(6)
      ).call(g =>
        g.selectAll(".tick text")
          .attr("text-anchor", (d, i) => this.variables[i].value < 0 ? "start" : "end")
          .attr("x", (d, i) => this.variables[i].value < 0 ? 6 : -6)
      )
    },
    updateBoundingBox() {
      this.$nextTick(() => {
        const svg = this.$refs.svg
        const bbox = svg.getBBox()
        svg.setAttribute("viewBox", `${bbox.x} ${bbox.y} ${bbox.width} ${bbox.height}`)
        svg.style.width = bbox.width + "px"
      })
    },
  },
  directives: {
    call(el, binding) {
      d3.select(el).call(binding.value)
    }
  }
}
</script>
